server:
  port: 8003
spring:
  application:
    name: selltickets

# org.springframework.cloud.netflix.eureka.EurekaClientConfigBean
eureka:
  instance:
    prefer-ip-address: true
  #hostname: eurekaserver
  client:
    #register-with-eureka: false #不把自己注册到eureka上
    #fetch-registry: false #不从eureka上获取服务的注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/
